name: Keep Backend Alive

on:
  schedule:
    # This runs every 7 Min
    - cron: '*/7 * * * *'
  workflow_dispatch: # This allows you to run it manually to test

jobs:
  ping_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the Backend
        run: |
          echo "Pinging backend to keep it awake..."
          curl -I "https://demo-deployment-w5ga.onrender.com/health"
